### ISSUE TITLE
Sirius: Copy/Delete/Move representation when done to model.

### ISSUE THREAD

**Issue by philippniethammer** [CoWolf/CoWolf#377]
When a model file is copied/deleted/moved, the representation file must be updated to match.

follows #386 
refs #372

**Comment by verenya** [comment]
It is not possible to update the representation and keep the layout
- First approach: copy the aird file and manually update the target of the diagram. 
  Problem: The copy function disguises as an add and this causes the aird file to delete all existing layouts. The change of the target does not change or prevent this.
- Second approach: Create a new aird file and use a MoveRepresentationComand to move the representation to the new aird file
  Problem: The session of the old aird files does not find any representations any more. As the matching resource does not exist any more, the result of the getRepresentations() is alway empty. And it's not possible to move nothing :-)

Possibilities: 
- Rename and move the aird file with the resource and lose the layout
- Just reset the target. Problem with this: It only works one time, afterwards we cannot find the matching aird file anymore, because it is named differently.

**Comment by philippniethammer** [comment]
Works fine for me manually:
- copy model file (My.ctmc -> My2.ctmc)
- copy .aird file of the model (My.ctmc.aird -> My2.ctmc.aird)
- open My2.ctmc.aird in text editor (DO NOT OPEN A SIRIUS SESSION)
- search & replace My.ctmc -> My2.ctmc
- save
- open Sirius session (double click on .aird) & open diagram.

**Comment by timsanwald** [comment]
I have testet a scenario, which works for me to copy the representation to another model. Maybe you can test it and eventually implement it:

It's also described in the user documentation of sirius at
http://www.eclipse.org/sirius/doc/user/diagrams/Diagrams.html#Copypasteoflayout
1. Create a dtmc, let's call it My.dtmc
2. Added states and transitions to the graphical presentation
3. Copied My.dtmc  to My1.dtmc
4. Right Click on My1.dtmc -> "Create Graphical Representation"
5. Opened the graphical editor of My1.dtmc (initial state of a model representation, all in one line)
6. Goto the My.dtmc graphical editor and right click into empty space
7. Choosed Edit -> "copy layout"
8. Goto My1.dtmc graphical editor and open popup menu
9. Choose Edit -> "paste layout"

**Comment by verenya** [comment]
I didn't think of the copy option for the aird file instead of a plain rename. I'll have a try with this. 
The copy layout method is probably more difficult to implement

**Comment by timsanwald** [comment]
Okay, i would suggest not to waste too much time on this. Just create the model on copy with versions and a representation files, the layout can be copied by the user if wished.

**Comment by verenya** [comment]
The copy of the layout does not work when the file is renamed. Then I don't have the original file to open the editor on...

**Comment by verenya** [comment]
Ok I tried a little bit:
A copy is no problem, I can also reset the according semantic model file. 
But: When doing this, the layout is lost :-( 
Only remaining solution: Programmatically read the file and replace the strings...

**Comment by verenya** [comment]
Very strange: Sometimes the model entry in the xml file gets deleted. I think Sirius has a listener and when the model gets renamed/moved, it removes the entry in the xml file as the model does not exist any more. When we are faster than the Sirius listener, the replacing in the file works fine...

**Comment by verenya** [comment]
Works :-)
